# Generated by Django 5.1.7 on 2025-04-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('ALTERNANCE', 'Alternance'), ('STAGE', 'Stage')], default='CDI', max_length=20),
        ),
    ]
