# Generated by Django 5.1.7 on 2025-04-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_candidature_type_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='ville',
            field=models.CharField(default='', max_length=255),
        ),
    ]
